### ISSUE TITLE
Placeholder problem

### ISSUE THREAD

**Issue by BinWayne** [IBM-Bluemix-Docs/databases-for-elasticsearch#1]
hi  Team
I saw all the *.md files have the placeholder issue.
Would you please help check it ?

such like in  
https://github.com/IBM-Bluemix-Docs/databases-for-elasticsearch/blob/master/howto-migration.md
------
{{site.data.keyword.cloud}} Object Storage bucket, and perform a restore of the snapshot to the {{site.data.keyword.databases-for-elasticsearch}} deployment.

------

**Comment by DailyAlice** [comment]
The place holder seems to be rendering just fine in the production docs. 
https://cloud.ibm.com/docs/services/databases-for-elasticsearch?topic=databases-for-elasticsearch-compose-migrating

Perhaps this was fixed at some point in the interim.
